# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    id: "upterm"
    binary: upterm
    main: ./cmd/upterm
    ldflags:
      - -s -w -X github.com/owenthereal/upterm/upterm.Version={{.Version}}

  # - env:
  #     - CGO_ENABLED=0
  #   goos:
  #     - linux
  #     - darwin
  #   id: "uptermd"
  #   binary: uptermd
  #   main: ./cmd/uptermd
  #   ldflags:
  #     - -s -w -X github.com/owenthereal/upterm/upterm.Version={{.Version}}

archives:
  # - format: tar.gz
  #   id: tar.gz
  #   name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  #   files:
  #     - etc/*
  #     - LICENSE
  #     - README.md
  #     - docs/*

  - format: binary
    id: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

# brews:
#   - tap:
#       owner: owenthereal
#       name: homebrew-upterm
#     commit_author:
#       name: Owen Ou
#       email: o@owenou.com
#     homepage: https://upterm.dev
#     description: Secure terminal sharing
#     folder: Formula
#     license: "Apache 2.0"
#     custom_block: |
#       head "https://github.com/owenthereal/upterm.git"
#     install: |
#       bin.install "upterm"
#       prefix.install_metafiles
#       bash_completion.install "etc/completion/upterm.bash_completion.sh"
#       zsh_completion.install "etc/completion/upterm.zsh_completion" => "_upterm"
#       man.install "etc/man/man1"
#     test: |
#       assert_match(/Upterm version/, shell_output("#{bin}/upterm version"))
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

publishers:
  - name: s3cmd
    cmd: s3cmd put {{ abs .ArtifactPath }} s3://{{ .Env.BUCKET }}/dist/upterm/releases/download/{{.Version}}/{{ .Binary }}_{{ .Os }}_{{ .Arch }}
